name: Build Original Telegram with Modifications

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-telegram:
    runs-on: macos-latest
    
    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4
      
    - name: Clone original Telegram iOS
      run: |
        echo "📥 Cloning original Telegram iOS..."
        git clone https://github.com/TelegramMessenger/Telegram-iOS.git original-telegram
        cd original-telegram
        git submodule update --init --recursive
        
    - name: Apply modifications
      run: |
        echo "🔧 Applying modifications..."
        cd original-telegram
        # Изменяем "Chats" на "ch"
        sed -i '' 's/"DialogList.TabTitle" = "Chats";/"DialogList.TabTitle" = "ch";/g' Telegram/Telegram-iOS/en.lproj/Localizable.strings
        sed -i '' 's/"DialogList.Title" = "Chats";/"DialogList.Title" = "ch";/g' Telegram/Telegram-iOS/en.lproj/Localizable.strings
        echo "✅ Modifications applied: 'Chats' → 'ch'"
        
    - name: Verify changes
      run: |
        echo "🔍 Verifying changes..."
        cd original-telegram
        grep -n "DialogList.TabTitle\|DialogList.Title" Telegram/Telegram-iOS/en.lproj/Localizable.strings
        
    - name: Setup Xcode
      run: |
        echo "📱 Setting up Xcode..."
        sudo xcode-select --switch /Applications/Xcode.app
        xcodebuild -version
        
    - name: Generate Xcode project
      run: |
        echo "🔨 Generating Xcode project..."
        cd original-telegram
        python3 build-system/Make/Make.py \
          --cacheDir="$HOME/telegram-bazel-cache" \
          generateProject \
          --configurationPath=build-system/template_minimal_development_configuration.json \
          --xcodeManagedCodesigning
        
    - name: Build Telegram iOS
      run: |
        echo "📦 Building modified Telegram iOS..."
        cd original-telegram
        xcodebuild \
          -project Telegram.xcodeproj \
          -scheme Telegram \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          build
        
    - name: Find build artifacts
      run: |
        echo "🔍 Looking for build artifacts..."
        cd original-telegram
        find . -name "*.app" -type d
        find . -name "*.ipa" -type f
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: modified-telegram-ios
        path: original-telegram/build/
        if-no-files-found: warn
        
    - name: Upload modified source
      uses: actions/upload-artifact@v4
      with:
        name: modified-source
        path: original-telegram/Telegram/Telegram-iOS/en.lproj/Localizable.strings
        
    - name: Success message
      run: |
        echo "🎉 Modified Telegram iOS build completed!"
        echo "📱 Changes applied: 'Chats' → 'ch'"
        echo "📥 Download from: GitHub Actions → Artifacts"
        echo "📋 Files:"
        echo "   - modified-telegram-ios: Build artifacts"
        echo "   - modified-source: Modified localization file" 