name: Build Telegram Simple (No Problematic Submodules)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-telegram-simple:
    runs-on: macos-latest
    
    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4
      
    - name: Clone original Telegram iOS
      run: |
        echo "📥 Cloning original Telegram iOS..."
        git clone https://github.com/TelegramMessenger/Telegram-iOS.git original-telegram
        cd original-telegram
        
    - name: Skip problematic submodules
      run: |
        echo "⚠️ Skipping problematic submodules..."
        cd original-telegram
        
        # Удаляем проблемные сабмодули из .gitmodules
        sed -i '' '/submodules\/TgVoipWebrtc\/tgcalls/d' .gitmodules || echo "tgcalls removal failed"
        sed -i '' '/submodules\/rlottie\/rlottie/d' .gitmodules || echo "rlottie removal failed"
        sed -i '' '/third-party\/webrtc\/webrtc/d' .gitmodules || echo "webrtc removal failed"
        
        # Обновляем только безопасные сабмодули
        git submodule update --init build-system/bazel-rules || echo "bazel-rules failed"
        git submodule update --init submodules/LottieCpp || echo "LottieCpp failed"
        git submodule update --init third-party/XcodeGen || echo "XcodeGen failed"
        git submodule update --init third-party/dav1d || echo "dav1d failed"
        git submodule update --init third-party/libvpx || echo "libvpx failed"
        git submodule update --init third-party/td || echo "td failed"
        
        echo "✅ Safe submodules updated"
        
    - name: Apply modifications
      run: |
        echo "🔧 Applying modifications..."
        cd original-telegram
        # Изменяем "Chats" на "ch"
        sed -i '' 's/"DialogList.TabTitle" = "Chats";/"DialogList.TabTitle" = "ch";/g' Telegram/Telegram-iOS/en.lproj/Localizable.strings
        sed -i '' 's/"DialogList.Title" = "Chats";/"DialogList.Title" = "ch";/g' Telegram/Telegram-iOS/en.lproj/Localizable.strings
        echo "✅ Modifications applied: 'Chats' → 'ch'"
        
    - name: Verify changes
      run: |
        echo "🔍 Verifying changes..."
        cd original-telegram
        grep -n "DialogList.TabTitle\|DialogList.Title" Telegram/Telegram-iOS/en.lproj/Localizable.strings
        
    - name: Setup Xcode
      run: |
        echo "📱 Setting up Xcode..."
        sudo xcode-select --switch /Applications/Xcode.app
        xcodebuild -version
        
    - name: Generate Xcode project
      run: |
        echo "🔨 Generating Xcode project..."
        cd original-telegram
        python3 build-system/Make/Make.py \
          --cacheDir="$HOME/telegram-bazel-cache" \
          generateProject \
          --configurationPath=build-system/template_minimal_development_configuration.json
        
    - name: Build Telegram IPA
      run: |
        echo "📦 Building Telegram IPA for iOS devices..."
        cd original-telegram
        
        # Копируем exportOptions.plist
        cp ../../ios/exportOptions.plist Telegram/Telegram-iOS/exportOptions.plist
        
        # Собираем архив
        xcodebuild -project Telegram.xcodeproj -scheme Telegram -configuration Debug -archivePath build/Telegram.xcarchive archive
        
        # Экспортируем IPA
        xcodebuild -exportArchive -archivePath build/Telegram.xcarchive -exportPath build/ipa -exportOptionsPlist Telegram/Telegram-iOS/exportOptions.plist
        
    - name: Find IPA files
      run: |
        echo "🔍 Looking for IPA files..."
        cd original-telegram
        find . -name "*.ipa" -type f
        ls -la build/ipa/ || echo "IPA directory not found"
        
    - name: Upload IPA file
      uses: actions/upload-artifact@v4
      with:
        name: telegram-simple-ipa
        path: original-telegram/build/ipa/*.ipa
        if-no-files-found: warn
        
    - name: Success message
      run: |
        echo "🎉 Simple Telegram IPA build completed!"
        echo "📱 Changes applied: 'Chats' → 'ch'"
        echo "📦 IPA file ready for iOS devices"
        echo "📥 Download from: GitHub Actions → Artifacts → telegram-simple-ipa"
        echo ""
        echo "✅ You now have Telegram with 'ch' button!" 